[package]
name = "test_test"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.67.1"

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.4", features = ["shell-open"] }
log = { version = "0.4.20", features = ["std"] }
rusqlite = { version = "0.29.0", features = ["bundled", "trace", "backup"] }
chrono = "0.4.31"

[dev-dependencies]
uuid = { version = "1.4.1", features = ["v4"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
